version: '3.9'
services:
  ip:
    build:
      args:
        build: false
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    volumes:
      - ./src:/app/src
